[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Clean URLs
[[redirects]]
  from = "/posts"
  to = "/posts.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/instruments"
  to = "/instruments.html"
  status = 200
