[build]
  command = "mkdir -p src/styles && cp styles/tailwind.css src/styles/tailwind.css"
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
