/**
 * GENERATED by scripts/write-build-flags.mjs during `npm run build`. Do not edit.
 *
 * Netlify's netlify.toml variables are build-time only; functions never see
 * them. This carries the build's answer into the bundle. See that script.
 */

/** Whether this deploy reads from Postgres rather than Netlify Blobs. */
export const USE_POSTGRES = false;
